### ISSUE TITLE
remoteHost invalid argument

### ISSUE THREAD

**Issue by egcodes** [calimero-project/calimero-core#50]
It gives an error when I give the ip address like the comment.

```
  /**
     * Specifies the KNX server, either as host name or IP address, 
     * used for access to the KNX network. Replace the string with an actual host/address of yours. For example, if you know the IP address
     * of your KNXnet/IP server, use something like "192.168.1.20".
     */
    private static final String remoteHost = "192.168.100.98";
```

> This example shows how to establish a KNX connection to a KNXnet/IP server.
Try connecting to 192.168.100.98 ...
Error connecting to 192.168.100.98: on connect to /192.168.100.98:3671: Invalid argument (sendto failed)

**Comment by calimero-project** [comment]
This is likely caused by trying to send over a different local network interface than what you expect, e.g., loopback interface.

In the introduction, there is another example called _Create a KNX link (with more options)_ ([CreateKnxLink2.java](https://github.com/calimero-project/introduction/blob/master/examples/CreateKnxLink2.java)) which let's you specify the local IP, too. Maybe try that.
