### ISSUE TITLE
KNX binding fails on sending PercentType to DPT 5.001

### ISSUE THREAD

**Issue by lewie** [calimero-project/calimero-core#53]
@bmalinowsky, could this be a bug?

["It's debatable if this is a bug in Calimero, because the Exception is originating in Calimero. It tries to decode the String to a Short, which fails for non-integer values."](https://github.com/openhab/openhab1-addons/issues/5417)

Thank You!

**Comment by bmalinowsky** [comment]
Yes, decimals could be handled better for the _scaling_ and _angle_ types. I put a commit to [calimero-core/fix/dpt-5.x.](https://github.com/calimero-project/calimero-core/tree/fix/dpt-5.x)

The changes are that now all values (not just type 5.001) are parsed as double and rounded where required. Internally, the representation remains _as-is_ ofc. Now, the translator also returns non-truncated values from `::getNumericValue`. The return value of `::getValue` I changed to FPN output but is limited to 1 decimal, because I think the standard formatting for FPNs does not really add a lot information for this DPT.

If you have time, I would appreciate feedback if the new parsing/formatting would be of any concern or cause problems for you?

Thanks for your report!
