### ISSUE TITLE
Local connection

### ISSUE THREAD

**Issue by ViorelOnica** [calimero-project/calimero-core#82]
Hello ! 

Is there any way I can find if I'm in the same network with my knx device or not ?

**Comment by bmalinowsky** [comment]
There is no built-in function that checks that. But if you open a connection with the local endpoint being the anylocal address, the connection will use a network interface on the same subnet.

On the command line, you can use a command like _traceroute_. Otherwise, in Java, you can query the subnet mask and manually compare the two IP addresses (local and knx device) according to that.

**Comment by ViorelOnica** [comment]
Thank you !
