### ISSUE TITLE
Implementation of TranslatorTypes#loadTranslators() with jar in jar

### ISSUE THREAD

**Issue by barni** [calimero-project/calimero-core#83]
Hello,

I used 2.4-rc2. I seems that the implementation of TranslatorTypes#loadTranslators()  doesnt work with jar in jar packaging. In that case base url doesnt match I think. My workarroung was to unpack the climero jar and package it in my app.

Stacktrace without doing that:
tuwien.auto.calimero.KNXException: no DPT translator available for main number 9 (ID 9.004)
        at tuwien.auto.calimero.dptxlator.TranslatorTypes.createTranslator(TranslatorTypes.java:571) ~[calimero-core-2.4-rc2.jar!/:na]
        at nrw.andresen.knx.services.knx.KnxController.handleMsg(KnxController.java:136) ~[classes!/:0.1.0-SNAPSHOT]

Cheers,
Stephan

**Comment by bmalinowsky** [comment]
This is a known limitation/inconvenience when loading jars within jars [within jars ...]. An implementation of this in calimero would also create a temporary exploded jar,  which is something I'm not sure people would always want. 

Your workaround is completely fine; otherwise, if you have a way to access the translators you need, `TranslatorTypes::getAllMainTypes` allows to add/remove translators at any time.
